<a href="https://colab.research.google.com/github/PINUMALLASAITEJA/ML_24AG5A6614/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to NumPy FrameWork



Import NumPy in Python

In [1]:
import numpy as np

NumPy Array Creation

In [2]:
array1 = np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


Create a 2-D NumPy Array

In [3]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Create a 3-D NumPy Array

In [4]:
array = np.array([[[1,2,3,4,5],[6,7,8,9,10],[1,6,2,5,3]] , [[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]]])
print(array)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 1  6  2  5  3]]

 [[ 1  2  3  4  5]
  [ 2  3  4  5  6]
  [ 3  4  5  6  7]]]


Check Data Type of a NumPy Array

In [5]:
array = np.array([1,2,3,4,5])
print(array.dtype)

int64


Check Size of Numpy array

In [6]:
array = np.array([1,2,3,4,5,6,7,8])
print(array.size)

8


NumPy Array shape Attribute

In [7]:
array = np.array([[1,2,3,4,5],[1,3,4,5,8]])
print(array.shape)

(2, 5)


NumPy Array itemsize Attribute

In [8]:
array = np.array([1,2,3,4])
array2 = np.array([1,2,3,4,5,6,7,8],dtype=np.int32)
print(array.itemsize)
print(array2.itemsize)

8
4


NumPy Array data Attribute

In [10]:
array = np.array([1,2,3,4,5])
array2 = np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(array.data)
print(array2.data)

Access Array Elements Using Index

In [11]:
array = np.array([1,2,3,4,5])
print(array[0])
print(array[2])
print(array[4])

1
3
5


Modify Array Elements Using Index



In [12]:
array = np.array([1,2,3,4])
array[0] = 5
print(array)

[5 2 3 4]


Compute Median Using NumPy

In [13]:
array = np.array([3,4,5,6,7])
median = np.median(array)
print(median)

5.0


Compute Mean Using NumPy

Standard Deviation of NumPy Array

In [16]:
array = np.array([3,4,5,6,7])
std = np.std(array)
print(std)

1.4142135623730951


Numpy Percentile

In [21]:
array = np.array([3,4,8,6,7])
percent = np.percentile(array,50)
print(percent)

6.0


Numpy min

In [19]:
array = np.array([3,4,5,6,7])
std = np.min(array)
print(std)

3


Compute Mean Using NumPy

In [22]:
array = np.array([2,4,5,6,7])
mean = np.mean(array)
print(mean)

4.8


Numpy max

In [20]:
array = np.array([3,4,5,6,7])
max = np.max(array)
print(max)

7
